### ISSUE TITLE
Soap call with non-english characters

### ISSUE THREAD

**Issue by amarbader** [doedje/jquery.soap#105]
Hi,

Calling the soap service is returning a gibberish characters instead of the right ones:
The server side is:
![unnamed](https://cloud.githubusercontent.com/assets/20257054/19624965/bcf83f8a-9913-11e6-8c96-b54b7539d795.png)

What I am getting in the client side as a response is:
![untitled1](https://cloud.githubusercontent.com/assets/20257054/19624976/078d7c68-9914-11e6-9ee6-4591f12c13b4.png)

I tried to change the "Content-Type" in the soap call header request by adding the following:
        HTTPHeaders: {
            'Content-Type': "application/json;charset=ISO-8859-6"
        }

But this didn't affect the "Request Header":
![untitled2](https://cloud.githubusercontent.com/assets/20257054/19625004/c60c4a70-9914-11e6-9a6d-8d1e8c417772.png)

I will appreciate for your advice.
Thanks,
Amar

**Comment by doedje** [comment]
I did my best to implement a new `charset` parameter for the `$.soap`-call but I was unsuccessful... After some googling I found out it is impossible....

>  Note: The W3C XMLHttpRequest specification dictates that the charset is always UTF-8; specifying another charset will not force the browser to change the encoding.

[from the $.ajax api specs](http://api.jquery.com/jquery.ajax/)

I am sorry...
