### ISSUE TITLE
NOT RUN IN FIREFOX AND CHROME ?

### ISSUE THREAD

**Issue by miltonmagalhaes** [doedje/jquery.soap#106]
I can only perform routine soap consumption by Internet Explorer. In Firefox and Chrome does not work.

**Comment by doedje** [comment]
do you have a link to an example of this? I basically use firefox to develop anyhting... I am on a mac, so IE is not even in the picture :) Without a testable case I will close this issue...

**Comment by doedje** [comment]
did you read [this](https://github.com/doedje/jquery.soap#contacting-me)? you are close to being #18'd (which means I don't like your tone, with all caps and much complaining but ZERO info on your case)
