### ISSUE TITLE
how can i choose a method to call my soap api? like GET or POST

### ISSUE THREAD

**Issue by praveenkumarS7** [doedje/jquery.soap#112]

**Comment by doedje** [comment]
The current version of jQuery.soap only supports POST.
```
273				type: "POST",
```
Do you need GET?

**Comment by doedje** [comment]
I'll close this issue when I don't receive any feedback....

**Comment by praveenkumarS7** [comment]
there is no way to call soap api in angular2. Better u can go for jquery soap
