### ISSUE TITLE
Posible enhancement? - $.soap in Angular (or Angular 2)

### ISSUE THREAD

**Issue by juankza95** [doedje/jquery.soap#113]
### Posible enhancement? - $.soap in Angular (or Angular 2)

This is only a request as enhancement. I'm able to make it work in AngularJS (not version 2) but a bit buggy. I would like to see this plugin as an AngularJS module or service.

Any previsions or thoughts to do this?

Anyway, thanks for the plugin. I think it's the only mantained nowadays.

PD: Sorry for bad english (?)

**Comment by doedje** [comment]
Hi Juankza.... I am myself not using AngularJS. So to make $.soap work with AngularJS is just not on my bucketlist.... It does work with, you guessed it, jQuery! ;) I am more than happy to receive pull request to make $.soap compatible with stuff like AngularJS. So I would like to encourage you to be crazy and dive in!!! ;)

**Comment by juankza** [comment]
Well, I have it a bit messy 'cause it's not flexible but easier for me (I only call a function that makes the request with some parameters).

By the moment i can't make it as pull request :( (and idk how too xd)

Would be better to make a pull request or make myself a repo with your plugin (referencing it, obviously)? I'm affraid to get issues that I can't resolve, I'm not a master in AngularJS but I see that for you is worst.

(the code it's about 50 lines, I think that it's not a full wrapper plugin)

**Comment by doedje** [comment]
It's all fine by me. If it's just (partly) wrapping the plugin you could just publish your code in a repo... but expect you needed to change some of the code to the plugin? Still interested to see the code, maybe we could make a proper enhancement out of it?

**Comment by doedje** [comment]
closing this for now, feel free to open when improvement is there....
