### ISSUE TITLE
cors error when running code

### ISSUE THREAD

**Issue by gcp2000** [doedje/jquery.soap#114]
XMLHttpRequest cannot load http://10.10.9.169/UserService3/WebService1.asmxgetUserbyUsername. Request header field SOAPAction is not allowed by Access-Control-Allow-Headers in preflight response.
jquery.soap.js:456 Uncaught Error: Unexpected Content: undefined

how to approach this error?

**Comment by doedje** [comment]
I don't know, all I see is an error message. I need a bit more context to have any clue on what you might be trying  to do. Here are some suggestions:

- [google your error-message](http://lmgtfy.com/?q=Request+header+field+SOAPAction+is+not+allowed+by+Access-Control-Allow-Headers+in+preflight+response)
- [please follow this little guide on contacting me from the README file](https://github.com/doedje/jquery.soap#contacting-me)

**Comment by doedje** [comment]
closing this issue when I don't get feedback...
