### ISSUE TITLE
Please disable the useless OPTIONS request by default

### ISSUE THREAD

**Issue by andreszs** [doedje/jquery.soap#115]
If I've understood a post here correctly, the useless **OPTIONS** request called endlessly every single time to delay our apps and waste bandwidth is just _to see if_ the developer knows how to configure his server:

> _The OPTIONS call is done to see whether you are allowed to access the service from another origin_

**Following this preposterous logic**, the library should also make a request to avast.com to check if my antivirus is up-to-date, or check if I have the latest browser version... an uttermost nonsense, like the OPTIONS request.

Please tell me there's a relatively easy way to **disable** this incredibly counter-productive _feature_, and how to do it. With all due respect, **let me worry about my server, and "see if" it blocks or allows CORS, please**.

We appreciate your concern, it's a cute detail for new developers who make their first _Hello world_ app with SOAP... but do we really need to **duplicate the amount of time and connections** just for this? It's a major annoyance for those who know what we are doing. I strongly advise to disable this by default; a brief paragraph in the **docs** about CORS will effectively address your concern for _Hello world_ app developers.

**Comment by doedje** [comment]
Dude, I love your rant, but you might want to educate yourself, (really). It's not jquery.soap doing this OPTIONS request, it's your browser, any browser for that matter. And it will do so EVERYTIME you want to make a cross-origin call... SO if you want to get rid of these (really minimal calls, hardly any payload, just headers) don't use CORS. Use a proxy. (nginx is cool for that kind of stuff) But don't go blaming me or jquery.soap for abusing your server for useless OPTIONS requests, cause there is only one guy to blame for not understanding CORS and waisting your servers cpu and bandwidth, sorry about it, but it's you!
So there you go, with your arrogance and aggressive tone. Totally out of place. Against somebody that wrote a library that is probably making your live easier. Showing no respect, and most important, showing NO KNOWLEDGE of http, soap, browsers, servers, cors, etc. etc....
Dude, really, who is the _Hello world_ app developer here? You just totally proved to understand shit.... good luck!

**Comment by doedje** [comment]
If you had read and understood #97 you would at least have any understanding of what the F* is going on in the browser in the case of a cross-origin call (when cors kicks in....)
I don't like your tone, I am not going to tell you how the internet works... You google that yourself and try to learn....

**Comment by doedje** [comment]
I love it how this LOSER never got around to actually answer me. Poor bastard....
