### ISSUE TITLE
Are you planning to publish the last version on npm registry??

### ISSUE THREAD

**Issue by cristianzamar** [doedje/jquery.soap#124]
Hi! I had some troubles with _version 1.6.9_, which I installed using `npm`, and then found that the last version works perfectly.
Are you planning to publish it? Why didn't you do it after upgrading??

PD: sorry for posting this question as issue, but I couldn't find any communication channel.

**Comment by doedje** [comment]
Sorry for the insanely late reply... I published 1.7.1 to npm! ;)
