### ISSUE TITLE
Support for Bare parameter style

### ISSUE THREAD

**Issue by Melnorme1984** [doedje/jquery.soap#125]
I'd like to use your script with a server that uses the Bare parameter style. That means the parameter is the only element inside the request XML body, instead of being under a root element with the same name as the SoapAction. The only way to do this now seems be to write the entire request envelope myself using the data option...

**Comment by doedje** [comment]
I did some reading about BARE vs WRAPPED parameters but as far as I understand the actual soap requests are exactly the same....

**Comment by Melnorme1984** [comment]
They're not. I described the difference in my original post. This is how I have to do it now:

```
var xml = ['<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">',
            '<S:Body>',
            '<ns2:baseNetworkName xmlns:ns2="network">',
            network + ".net",
            '</ns2:baseNetworkName>',
            '</S:Body>',
            '</S:Envelope>'];

$.soap({
            "url": anatURL,
            "SOAPAction": '"getXref"',
            "data": xml.join("")

            "success": function (soapResponse) {
                ...
            }
        });
```
There's no container XML element inside the Body that contains the parameter. The parameter itself (`baseNetworkName)` is the container.

**Comment by doedje** [comment]
It should be enough to do just (without the repeating the Envelope and Body tag all the time):

```
$.soap({
            "url": anatURL,
            "SOAPAction": '"getXref"',
            "data": '<ns2:baseNetworkName xmlns:ns2="network">' + network + ".net" + '</ns2:baseNetworkName>'

            "success": function (soapResponse) {
                ...
            }
        });
```

that is about as bare as I can make it... ;)

**Comment by Melnorme1984** [comment]
Well that's better, but it would be nice if there was native support that allowed you to use `method`, `namespaceQualifier` and son.

**Comment by doedje** [comment]
I'll look into that, are you planning to do requests with multiple parameters?

**Comment by doedje** [comment]
I currentlty have made a change to the script that allows to do this:

```
$.soap({
  url: anatURL,
  method: "baseNetworkName",
  SOAPAction: "getXref",
  data: "test.net",
  namespaceQualifier: "ns2",
  namespaceURL: "network",

  success: function(soapResponse) {
    ...
  }
});
```

Which results in this SOAP Request being send:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <ns2:baseNetworkName xmlns:ns2="network">test.net</ns2:baseNetworkName>
  </soap:Body>
</soap:Envelope>
```

But as soon as you might want to send more than one parameter, this is not going to help you.

**Comment by Melnorme1984** [comment]
Great, thanks.

It's not possible to have more than one parameter with this method. That's sort of the point!

**Comment by doedje** [comment]
Normal behavior for the script is like this:

`method` is: 

- used as the `method` which is appended to the url, disable this by setting `appendMethodToUrl` to `false`
- used as the `SOAPAction`, explicitly set `SOAPAction` yourself to overrule this one.
- used as the `elementName`, explicitly set `elementName` yourself to overrule this one.

(from https://github.com/doedje/jquery.soap/blob/master/doc/options.md#method)

The code does implicitly recognize the bare parameter style when the `data` is a string but does not contain a `<` aka is not an XML String.

The SOAPRequest from my previous post could also be created with this call:

```
$.soap({
  url: anatURL,
  method: "getXref",
  namespaceQualifier: "ns2",
  namespaceURL: "network",
  elementName: "baseNetworkName",
  data: "test.net"
});
```

Download the 1.7.2 version of **$.soap** and you're of to the races....
