### ISSUE TITLE
getting Jquery is not defined error

### ISSUE THREAD

**Issue by spmanutd007** [doedje/jquery.soap#127]
`<!DOCTYPE html>
<html>

<head>
<script src="jquery.soap.js">

<script>
$.soap({
	url: 'http://www.thomas-bayer.com/axis2/services/BLZService',
	method: 'blz:getBank',

	data: {
		blz:blz: '10070100',
		
	},

	success: function (soapResponse) {
		// do stuff with soapResponse
		// if you want to have the response as JSON use soapResponse.toJSON();
		// or soapResponse.toString() to get XML string
		// or soapResponse.toXML() to get XML DOM
	},
	error: function (SOAPResponse) {
	   console.log("error in response");
		// show error
	}
});

</script>

</head>
</html>`

I am getting jquery is not defined. The script jquery.soap.js has been correctly referenced.Any ideas? Do i need to add any import statements in jquery.soap.js?

**Comment by doedje** [comment]
The documentation is not very clear on this. jQuery.soap is a jQuery plug-in. It requires you to load jQuery itself before loading any of the plugins. You do this in your html.....

**Comment by spmanutd007** [comment]
how to load jquery?? what should i write in src="" to load jquery?

**Comment by spmanutd007** [comment]
i solved the problem,just had to change the order of script tags to this-
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="jquery.soap.js">

**Comment by doedje** [comment]
Glad you fixed it... =]
