### ISSUE TITLE
Any way to do synchronous calls?

### ISSUE THREAD

**Issue by Velocedge** [doedje/jquery.soap#130]
Chrome's new release stops synchronous calls on onbeforeunload (FF to follow).  We're using SOAP in our SCORM runtime and the 3rd party courses (SCO's) make the call to our SCORM API expecting them to return data from the web service.  We were making the ajax call synchronously and now it won't work.  Is there any way we can change the SOAP call so it appears synchronous to the functions the SCO is calling?

**Comment by doedje** [comment]
Which version of Chrome are you using?

**Comment by doedje** [comment]
I am closing this one... I will rephrase what browser builders are saying: DON’T USE SYNC, IT’S BAD..... rewrite your code to be event-driven..... it’s not that hard and future proof...
