### ISSUE TITLE
Success function doesn't get run on success

### ISSUE THREAD

**Issue by dhuber666** [doedje/jquery.soap#133]
Hi man, 

it's me again. I fixed the cors problem and now I'm getting into the real business of the package. 

When I send my request it's working now (as I can see on the server). But the `success` function doesn't run. When I console.log it or debug it, it does not run. 

What am I missing.

Here is the code:

```
$.soap({
  url: "https://mycompany/webservice",
  method: "myMethod",
  HTTPHeaders: {
    Authorization: "Basic " + btoa(username + ":" + password)
  },

  data: {
    ...myValues
  },

  success: function(soapResponse) {
    console.log("we have success", soapResponse);
    console.log("hellooooo");
    // do stuff with soapResponse
    // if you want to have the response as JSON use soapResponse.toJSON();
    // or soapResponse.toString() to get XML string
    // or soapResponse.toXML() to get XML DOM
  },
  error: function(SOAPResponse) {
    console.log("this is the error", SOAPResponse);
  }
});
```

//EDIT: After further investigating I found out that the function does run. Because it's stopping when I put the debugger in it. But it does not console.log anything. That is super weird. (my guess is, the console is not ready yet when I want to log it, but why so?)

Also if I find a librarie that parses XML to JSON how can I gett access to the XML document returned by the soapResponse? Which key is it?

The `soapResponse` is an object like this:

![2019-11-25 14_25_15-Window](https://user-images.githubusercontent.com/15130832/69544179-7b348180-0f8f-11ea-91c0-ea46d492000d.png)

I would appreciate your help.

And thx again for the package my man.

**Comment by Steven2160** [comment]
Hi,

Does anyone get answer?
I got similar issue. When the method process in short time, success/error will be triggered but when the method processing too long (about > 10 sec), success/error will not be triggered. It shows "Session state: aborted" when I capture in fiddler. And the sessionState time out in web config doesn't take effect.

Thanks,
Steven

**Comment by doedje** [comment]
@dhuber666 I am sorry to have missed/forgotten about your issue and never got back to you... I hope you figured out how to fix your problem by now.. ;)

@Steven2160 I would need an example that reproduces your problem to be able to properly debug your case...

**Comment by Steven2160** [comment]
Hi @doedje,

I reviewed the solved issues and got a solution.
My problem can be resolved by add time out attribute.
![image](https://user-images.githubusercontent.com/16731920/83113497-4fd74e80-a0fa-11ea-914a-e966abf9f516.png)
Not sure if it will work for @dhuber666 .

Thanks,
Steven

**Comment by Steven2160** [comment]
Hi @doedje,

Just an additional question:
May I know how long is the default timeout for jquery.soap?

Thanks,
Steven

**Comment by doedje** [comment]
As stated in the documentation: https://github.com/doedje/jquery.soap/blob/master/doc/options.md#timeout or in the code of jquery.soap.js itself, line 57: 5000 ms.

**Comment by Steven2160** [comment]
Thanks @doedje. Already noticed it in the global config.
