### ISSUE TITLE
TypeError: $.soap(...).done is not a function

### ISSUE THREAD

**Issue by karres-illinois** [doedje/jquery.soap#134]
Hi, I have just started using jquery.soap. I have: "jquery": "^3.4.1" and "jquery.soap": "^1.7.3"

The Readme says that it honors the "promise" model.  I have the following:

`
function getLists() {
	$.soap({
		url: "https://lists.mycompany.com/listssoap",
		method: "lists",
	}).done(function(data, textStatus, jqXHR) {
		console.log("DONE");
	}).fail(function(jqXHR, textStatus, errorThrown) {
		console.log("FAIL");
	});
}
`

but when run i get the error in the subject.  Am I doing something wrong?

**Comment by doedje** [comment]
Hi, I must say I haven't tested the code with jQeury3.x yet (will have to in the coming months...)
As far as I understand from the jQuery website the underlying call, $.ajax, is still returning the jqXHR object that implements the Promise interface.
So your code should be okay. OR your call to $.soap doesn't return the jqXHR object?

You can check that like so:

```
function getLists() {
  var tmp = $.soap({
    url: "https://lists.mycompany.com/listssoap",
    method: "lists"
  });
  console.r(tmp);
}
```

(are you sure you don't run into Same-origin policy restrictions?)

**Comment by karres-illinois** [comment]
Hi

Thank you for the sample code.  I am getting an object returned.  Since reporting the issue I reverted back to the success/error methodes.  It seems like neither of those is being called.  A really strange thing is that this actually worked a lot earlier today – the success/error methods.
1.   Object
1.   appendMethodToURL: true
2.   async: true
3.   enableLogging: false
4.   noPrefix: false
5.   soap12: false
6.   withCredentials: false
7.   timeout: 5000
8.   url: "https://lists.mycompany.com/soap"
9.   namespaceURL: "https://lists. mycompany.com /lists/wsdl"
10. method: "lists"
11. success: ƒ (soapResponse)
1.   length: 1
2.   name: "success"
3.   arguments: null
4.   caller: null
5.   prototype: {constructor: ƒ}
6.   __proto__: ƒ ()
7.   [[FunctionLocation]]: site.js:288
8.   [[Scopes]]: Scopes[2]
12. error: ƒ (soapResponse)
1.   length: 1
2.   name: "error"
3.   arguments: null
4.   caller: null
5.   prototype: {constructor: ƒ}
6.   __proto__: ƒ ()
7.   [[FunctionLocation]]: site.js:311
8.   [[Scopes]]: Scopes[2]
13. __proto__: Object
Thanks, I’ll keep poking at it.

Cheers
