### ISSUE TITLE
can call wcf svc asp.net with this library?

### ISSUE THREAD

**Issue by habib8787** [doedje/jquery.soap#136]

**Comment by doedje** [comment]
Did you try??? Come on, if you want a decent answer, try asking a decent question.... Because I don't understand shit about what you want....
PLEASE NOTE THIS LIBRARY IS LICENSED GNU-GPLv3!
(this mostly means that you cannot use it in commercial product)

**Comment by habib8787** [comment]
hi.
yes i try to call but cant.
i have a asp.net svc wcf services and need to call methods with json input instead of xml.
something like this
http://localhost:44399/Services/Admin/AdminPanelService.svc
i can consume it in postman, but with xml input.
i need to pass json input. 
can i call like this wcf services with this library?
thanks for reply.

**Comment by doedje** [comment]
So you found yourself a hammer and are asking me weither you can use it as a screwdriver??

You send me an url to localhost?

My guess is you can use $.ajax for what you want to do.

Good luck...

**Comment by habib8787** [comment]
i think i cant explain what is in my mind.
yes, i can consume it with ajax, but with help of web method in c#. i want to call it directly from jquery and ajax.
i need more generic tool like this (jquery.soap) library.
i want to know can i call .svc service with this library? and if yes, how?
i used "jquery.soap-master/web/index.html" page but i cant consume my service.
could you help me to consume my service with this library and json input?
thanks a lot.

**Comment by doedje** [comment]
This lib is called jquery.soap for a reason: it uses SOAP to communicate with a service; it sends a SOAPRequest and expects a SOAPResponse in return. That is all it does. For convience you can use JSON to create a SOAPRequest and it is possible to convert the SOAPResponse it will get back to JSON. But when your service can't communicate SOAP you'll need another lib. When you want to communicate using JSON you're better off using jquery.ajax.
