### ISSUE TITLE
help with error: Request format is invalid: text/xml; charset=UTF-8

### ISSUE THREAD

**Issue by phonger** [doedje/jquery.soap#56]
![error](https://cloud.githubusercontent.com/assets/8622744/4113744/24376184-3256-11e4-903d-7a5a90bd3241.PNG)
Hello,

I am hoping you can help me with this issue I am having.
I am just trying to use jquery.soap to call this web service: http://www.w3schools.com/webservices/tempconvert.asmx?op=CelsiusToFahrenheit

I tried to use the jquery.soap demo page that is provided.
The error I got was: Request format is invalid: text/xml; charset=UTF-8

The settings I used for the demo page are:
url: http://www.w3schools.com/webservices/tempconvert.asmx/
method: CelsiusToFahrenhei
appendMethodToURL: checked
params: XML String

The Result that I see is: Request format is invalid: text/xml; charset=UTF-8.

If you have time, can you take a look at getting jquery.soap call that sample temperature web service?

thanks,
David

**Comment by lijibing01** [comment]
hi Remy
I tried out the latest version of jquery.soap.js. But I have the same problem. Please help me to explain
![image](https://user-images.githubusercontent.com/26105855/28764643-26c5a458-75f9-11e7-8083-185685d12056.png)
`var soapXML = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET"><soapenv:Header/><soapenv:Body><web:GetCitiesByCountry><web:CountryName>china</web:CountryName></web:GetCitiesByCountry></soapenv:Body></soapenv:Envelope>';
                console.log(soapXML);
                $.soap({
                    url : "http://www.webservicex.net/globalweather.asmx/",
                    method : "GetCitiesByCountry",
                    data: {
                        "CountryName":"china"
                    },
                    dataType:"xml",
                    processData: false,
                    success : function(data) {
                        alert("webmethod call success");
                    },
                    error : function(err) {
                        alert(err.toString());
                        console.log(err.toString());
                    }
                });`

**Comment by lijibing01** [comment]
If I pass the XML format is wrong
`var soapXML = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET"><soapenv:Header/><soapenv:Body><web:GetCitiesByCountry><web:CountryName>china</web:CountryName></web:GetCitiesByCountry></soapenv:Body></soapenv:Envelope>';
                console.log(soapXML);
                $.soap({
                    url : "http://www.webservicex.net/globalweather.asmx/",
                    method : "GetCitiesByCountry",
                    data: soapXML,
                    dataType:"xml",
                    processData: false,
                    success : function(data) {
                        alert("webmethod call success");
                    },
                    error : function(err) {
                        alert(err.toString());
                        console.log(err.toString());
                    }
                });`
![image](https://user-images.githubusercontent.com/26105855/28764735-a5d759f8-75f9-11e7-8d17-3cb2ef4148a9.png)

**Comment by lijibing01** [comment]
I also returned the same result with the postman test
![image](https://user-images.githubusercontent.com/26105855/28766267-673d2710-7601-11e7-8a78-9c96c7d3bc0e.png)

**Comment by doedje** [comment]
Sorry for the late reply, summer holidays kept me away from the computer!

I was able to use the jQuery.soap demo page that is supplied with jQuery.soap to get a successful call send to the service like this:

```
$.soap({
  url: "proxyPlus.php?url=http://www.webservicex.net/globalweather.asmx",
  method: "GetCitiesByCountry",
  appendMethodToURL: false,
  SOAPAction: "http://www.webserviceX.NET/GetCitiesByCountry",
  data: "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:web=\"http://www.webserviceX.NET\"><soapenv:Header/><soapenv:Body><web:GetCitiesByCountry><!--Optional:--><web:CountryName>netherlands</web:CountryName></web:GetCitiesByCountry></soapenv:Body></soapenv:Envelope>",
  enableLogging: true
});
```

please note that this example is using the proxyPlus.php script which is also included in the project which I had to tweak slightly... I had to use it because my localhost is using https and webserviceX is not.

**Comment by doedje** [comment]
Another way to have it work is this:

```
$.soap({
  url: "proxyPlus.php?url=http://www.webservicex.net/globalweather.asmx",
  method: "GetCitiesByCountry",
  appendMethodToURL: false,
  SOAPAction: "http://www.webserviceX.NET/GetCitiesByCountry",
  data: { CountryName: 'netherlands' },
  namespaceURL: "http://www.webserviceX.NET",
  noPrefix: true,
  enableLogging: true
});
```
This way you don't have to go thru the trouble of constructing the XML as a string, you let $.soap do that for you, you specify the data as a JSON object...

**Comment by lijibing01** [comment]
Hi Remy,

Thanks for your reply . I have solved this problem, just like the example of your reply. And I verified that WS-Security was correct.
