### ISSUE TITLE
Not be able to install latest versions by bower 

### ISSUE THREAD

**Issue by Aradesh** [doedje/jquery.soap#70]
Please add 1.4.4 and 1.5.0 tags
https://github.com/doedje/jquery.soap/releases

Now if you run bower install command it install 1.4.3, but when you want to edit the version to 1.5.0 in bower.json - it fails

$ bower install
bower not-cached    https://github.com/doedje/jquery.soap.git#1.5.0
bower resolve       https://github.com/doedje/jquery.soap.git#1.5.0
bower ENORESTARGET  No tag found that was able to satisfy 1.5.0

Additional error details:
Available versions: 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3
.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.7,
 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.10.0, 0.9.4, 0.9.3, 0.9.2, 0
.9.1, 0.9.0

**Comment by doedje** [comment]
I did another 'push all tags' and now the 1.4.4 and 1.5.0 show up on github and in bower:
```
$ bower info jquery.soap
bower cached        git://github.com/doedje/jquery.soap.git#1.3.8
bower validate      1.3.8 against git://github.com/doedje/jquery.soap.git#*
bower new           version for git://github.com/doedje/jquery.soap.git#*
bower resolve       git://github.com/doedje/jquery.soap.git#*
bower download      https://github.com/doedje/jquery.soap/archive/1.5.0.tar.gz
bower extract       jquery.soap#* archive.tar.gz
bower resolved      git://github.com/doedje/jquery.soap.git#1.5.0

{
  name: 'jquery.soap',
  version: '1.5.0',
  keywords: [
    'soap',
    'ajax',
    'wss'
  ],
  main: 'jquery.soap.js',
  dependencies: {
    jquery: '>=1.9'
  },
  homepage: 'https://github.com/doedje/jquery.soap'
}

Available versions:
  - 1.5.0
  - 1.4.4
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4.0
  - 1.3.10
  - 1.3.9
  - 1.3.8
  - 1.3.7
  - 1.3.6
  - 1.3.5
  - 1.3.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3.0
  - 1.2.2
  - 1.2.1
  - 1.2.0
  - 1.1.0
  - 1.0.7
  - 1.0.6
  - 1.0.5
  - 1.0.4
  - 1.0.3
  - 1.0.2
  - 1.0.1
  - 1.0.0
  - 0.10.0
  - 0.9.4
  - 0.9.3
  - 0.9.2
  - 0.9.1
  - 0.9.0

You can request info for a specific version with 'bower info jquery.soap#<version>'
```
