### ISSUE TITLE
statusCode 

### ISSUE THREAD

**Issue by AndersMygind** [doedje/jquery.soap#71]
Very nice plugin indeed!
I have a question concerning checking for statusCodes.
In $.ajax it is possible to include a function depending on statusCode getting back.
Do I have similar feature in your plugin?
Something like:

$.soap({	
    	data:t3,
    	statusCode : {
			500 : function() { //if it's not in the db
				s.erroruuidserviceShow.alert();
                	});  
			}
},

Thanks in advance!
best regards Anders Gram Mygind

**Comment by doedje** [comment]
fairly easy to implement, will do next monday... enjoying my weekend at the moment =]

**Comment by doedje** [comment]
(wrong button...)

**Comment by doedje** [comment]
Version 1.6.0 is now available and features the statusCode option as requested...
