### ISSUE TITLE
Untracked dependency xml2json?

### ISSUE THREAD

**Issue by perqa** [doedje/jquery.soap#74]
In the soapResponse object there is a method named toJSON(). If I call soapResponse.toJSON(), I get 
```
jQuery.soap: Missing JQuery Plugin 'xml2json'
````
Maybe that dependency should be installed when installing jQuery.soap? I used bower to install it.

I have googled for xml2json and there seems to be a few different libraries by that name. Which one should I use?

**Comment by doedje** [comment]
i get your point... I will look if there is a suitable xml2json plugin in the bower repo that I can mention as dependencie... I test and work with the one mentioned in the readme: 

https://github.com/doedje/jquery.soap#dependencies

Hope that works for you!

**Comment by doedje** [comment]
Seems the one I used was already published in bower by somebody, so I could add the dependency: Installing version 1.6.3 will now also install xml2json...
Still awaiting my pull request to [xtreem/jquery.xml2json](https://github.com/xtreemrage/jquery.xml2json) to be able to do the same for npmjs

**Comment by perqa** [comment]
Thanks for the quick response, and an absolutely fantastic plugin!

I tried xtreem/jquery.xml2json, but it crashes:
```
Uncaught ReferenceError: cnn is not defined           jquery.xml2json.js:87 
```

Im currently using https://github.com/josefvanniekerk/jQuery-xml2json, which seems to work fine.
