### ISSUE TITLE
Handling accented characters in soap response

### ISSUE THREAD

**Issue by DemarsM** [doedje/jquery.soap#77]
I got encoded accented characters in my soap response such `&#xC3;&#xA9;` for "é" or `&#xC3;&#xAB;` for "ë". I can't change the settings on server side.

When using  toJSON() or toString(), those accented characters are transformed to `Ã©` and `Ã«` instead of "é" and "ë".

How can I  get the correct UTF-8 character instead of those specials characters? Should I ask my question in xml2json support forum instead?

Thank you

**Comment by DemarsM** [comment]
Error is on server side that return wrongly encoded XML response

**Comment by doedje** [comment]
glad you solved it.... =]
