### ISSUE TITLE
Need xmlns on data obj

### ISSUE THREAD

**Issue by xDreamCoding** [doedje/jquery.soap#79]
Is there a way to do so?

data : { "arg1 xmlns="test" : "first", "arg2 xmlns=" test" : "second"}

Sorry writing this on mobile..

**Comment by doedje** [comment]
At the moment $.soap's inner json2soap function does not have a way to create attributes in the soap.
So you have two options:

1) specify `data` as an XML string:
```
data: '<data xmlns:test="first" xmlns:test2="second"></data>'
```
or 2) Use a third party json2xml converter that DOES support attributes (use google to find one):
```
data: json2xml({ "arg1 xmlns="test" : "first", "arg2 xmlns=" test" : "second"})
```
In this case you should ofcourse change the syntax to the way this third party converter wants to have the attributes specified...

Good luck
