### ISSUE TITLE
is there a reason of using `jquery.xml2json`?

### ISSUE THREAD

**Issue by wood1986** [doedje/jquery.soap#83]
Is there a reason of using `jquery.xml2json`? `jquery.xml2json` blocks from using latest jquery because of `"dependencies" : { "jquery": "1.11" }` in [xtreemrage/jquery.xml2json/bower.json](https://github.com/xtreemrage/jquery.xml2json/blob/master/bower.json) 

Would mind changing to use [sparkbuzz/jQuery-xml2json](https://github.com/sparkbuzz/jQuery-xml2json)?

**Comment by doedje** [comment]
sorry for late reply, summer holidayzzzzzzz..... But I wil look into that...

**Comment by doedje** [comment]
The jquery.xml2json plugin is only used for the SOAPResponse.toJSON() function. Changing it to sparkbuzz would definitely break other peoples code. But the fyneworks/xtreemrage version is quite crappy. It does fine with simple soap responses but fails massively at other XMLs I came across...

I think the best thing would be to drop the dependency altogether and add some additional info regarding the use of SOAPResponse in combination with a 3rd party jquery plugin like the sparkbuzz version in the README.......
