### ISSUE TITLE
JSON equivalent of XML attributes 

### ISSUE THREAD

**Issue by jadbaz** [doedje/jquery.soap#85]
Hello,
The documentation does not seem to say anything about this.
How can I specify attributes on nodes in 'data' when specifying them in JSON format?
For example:
<element attr1="ABC" attr2="XYZ" />

This would be { element: {} }.
How can I specify attr1 and attr2?

**Comment by doedje** [comment]
For now you have 2 options:

1) specify your data using XML:
```
<element attr1='foo' attr2='bar' />
```
2) use a third party json2xml converter and code like:
```
obj = {.....}; //see whatever syntax that plugin is using to specify attributes
$.soap({
  data: json2xml(obj);
});
```

**Comment by jadbaz** [comment]
Thank you very much

On Wed, Sep 16, 2015, 16:40 Remy Blom <notifications@github.com> wrote:

> For now you have 2 options:
>
> 1) specify your data using XML:
>
> <element attr1='foo' attr2='bar' />
>
> 2) use a third party json2xml converter and code like:
>
> obj = {.....}; //see whatever syntax that plugin is using to specify attributes
> $.soap({
>   data: json2xml(obj);
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/doedje/jquery.soap/issues/85#issuecomment-140745437>.
>
-- 

Jad
