### ISSUE TITLE
WSDL and Soap for beginner

### ISSUE THREAD

**Issue by funnix** [doedje/jquery.soap#89]
Hi i have build an SOAP Client by PHP on my home computer it works well, on my server not.;-( That`s why i want to try by client side js ;-) I do not realy understand SOAP , think too old for that;-)
I found your fork but no explanation how to do with WSDL ?!

I have an Service Provider , really undocumented, where i need to get an WSDL by an auth call.

Can you Help me how to use ?!

**Comment by doedje** [comment]
A WSDL is nothing more than a machine-readable description of the service provided: it tells you (or a program) what methods you can call and which elements are expected as input (the request) and what you can expect in return (the response). 

So when you want to work with $.soap you don't need to use a WSDL programmatically (you could if you want) but you can just use it as a reference, think of it as a really nerdy way to write a manual for a service.

Further reading about WSDL: https://en.wikipedia.org/wiki/Web_Services_Description_Language
