### ISSUE TITLE
SOAP Error

### ISSUE THREAD

**Issue by mustafizurrohman** [doedje/jquery.soap#90]
Hello,
 I am facing a problem while calling my asmx SOAP service. My javascript/ajax code is as follows:

	$.soap({
                url: "https://exampleurl.com/service1.asmx",       // url is correct 
                method: "examplemethod",                          // optional
                appendMethodToURL: false,                        // 404 error when set to 'true'
                soap12: true,                                   // SOAP 1.2 Request
                // SOAPAction: "http://tempuri.org/examplemethod", // Optional for 1.2
                // context: document.body,
                enableLogging: true,   // logging enabled for debugging

                 
                // For JSON
                data: {
                    parameter1 : 'data1',
					parameter3 : 'data2',
					parameter3 : 'data3',
					parameter4 : 'data4'
                }, 
                
                
                beforeSend: function (SOAPEnvelope) {
                    alert("Sending : \n\n\n" + SOAPEnvelope);
                    // console.log("Sending : \n\n\n" + SOAPEnvelope);
                },
                
                sucess: function (soapResponse) {
                    alert("SUCESSFUL SOAP Response : \n\n\n" + soapResponse);
                    // console.log("SUCESSFUL SOAP Response : \n\n\n" + soapResponse);
                },

                error: function (SOAPResponse) {
                    alert("FAILED SOAP Response : \n\n\n" + SOAPResponse)
                    // console.log("FAILED SOAP Response : \n\n\n" + SOAPResponse);
                },

                // callback functions based on statusCode
                statusCode: {                                   
                    404: function () {
                        alert('404 Not Found');
                        // console.log('404 Not Found');
                    },
                    200: function () {
                        alert('200 OK');
                        // console.log('200 OK');
                    }
                }
        });

 For this code I always get the following fail message:
```
<?xml version="1.0" encoding="utf-8"?>
	<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		<soap:Body>
			<soap:Fault>
				<soap:Code>
					<soap:Value>soap:Receiver</soap:Value>
				</soap:Code>
				<soap:Reason>
					<soap:Text xml:lang="en">
						The request could not be processed by the server. --- & gt; The root element is missing.
					</soap:Text>
				</soap:Reason>
				<soap:Detail/>
			</soap:Fault>
		</soap:Body>
	</soap:Envelope>
```
It would be nice if anyone could kindly shed some light on the error. I have been trying to fix this for the last few hours without success. Thank you. Cheers.

Mustafizur

**Comment by doedje** [comment]
My guess is you should set the method correctly, it should match a valid service operation name.

https://github.com/doedje/jquery.soap/blob/master/doc/options.md#method

**Comment by mustafizurrohman** [comment]
This was an example. I changed it to a real method name but unfortunately the problem is still there.

**Comment by doedje** [comment]
Than my advice would be to use the WSDL of your service in the [SoapUI application](http://http://www.soapui.org/) and see what the calls look like in there and try to recreate that with the jquery.soap demo page...
Example code like the one you provided is not helping me in seeing what might be wrong. The method suggestion was merely based on the `// optional' remark behind it.... =]

**Comment by doedje** [comment]
The `// optional` and the error message about a missing rootnode.... What does your outgoing XML look like?

**Comment by mustafizurrohman** [comment]
Thank you for your kind reply. Here is my outgoing XML.

![outgoingxml](https://cloud.githubusercontent.com/assets/12828222/10480901/4f5f1980-726d-11e5-9083-28d4714941df.jpg)

**Comment by doedje** [comment]
Hmm, might be needing a namespace for the resetAccount node.... Please try with WSDL and SoapUI... That shows you what the calls should look like..

**Comment by mustafizurrohman** [comment]
You are right. Absolutely right. It should be as follows :

<resetAccount xmlns="http://tempuri.org/">
		....
</resetAccount>

Kindly let me know who can I set it. Thank you very much.

**Comment by doedje** [comment]
add the following:
```
  namespaceURL: "http://tempuri.org",
```

By the way, to add xml or code to your comments on github you can use the following markdown: [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)
Saves you the trouble of making screenshots ;)

**Comment by mustafizurrohman** [comment]
Thank you very much. It still does not work, unfortunately.

**Comment by doedje** [comment]
try soapui, it really is great for debugging soap...

**Comment by mustafizurrohman** [comment]
Thank you. I will. Have a nice day!

**Comment by doedje** [comment]
you too, good luck and let me know when you do or don't succeed... One last suggestion I would like to give you is looking at the serverside.... Missing the root element might suggest the server is not receiving anything.... Or is looking for the soap message in the wrong place...

**Comment by doedje** [comment]
(can I close this issue? are you doing fine?)

**Comment by mustafizurrohman** [comment]
Sorry for my late response .. Unfortunately I could not get it to work and decided to use something else. Kindly close the issue. Thank you. Have a nice weekend!
