### ISSUE TITLE
Creating xml structure as more than 1 knot?

### ISSUE THREAD

**Issue by avdesign** [doedje/jquery.soap#91]
Hi, congratulations on the project, am new to jquery and am trying to create this type of call xml.
could help me create this structure. I thank you for your time.

<?xml version="1.0" encoding="utf-8"?>
soap12:Envelope >
  soap12:Body>
    SubmitInfo xmlns="http://www.dominio.com.br/integration">
      entityCode>string</entityCode>
      xmlDados>string</xmlDados>
    /SubmitInfo>
  /soap12:Body>
/soap12:Envelope>

**Comment by doedje** [comment]
Sorry if this might come over a bit blunt, but there is a saying on the internet which goes like this:

[RTFM!](http://lmgtfy.com/?q=RTFM)
============================

So you go over to: https://github.com/doedje/jquery.soap and READ!
Try to write some code. There is a demo page included in the project that could be helpful, it let's you play around with all the options of $.soap and even allows you to copy-paste the call you created... It couldn't be more simple. But I expect a little efford from your side, I am far to busy to help you from scratch. If you get stuck in the proces I am more than happy to review your code, help you to pinpoint the problems and guide you into the direction of your solution, but you are going to do the coding here, not me.... Hope you understand... =]

**Comment by avdesign** [comment]
Sorry for the inconvenience, really then review the code was very simple. thank you!
