### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by heinrichmartin** [doedje/jquery.soap#94]
http://usamadar.com/2012/06/24/getting-around-browsers-same-origin-policy-sop-with-proxies-script-injection-jsonp-and-cors/ is broken in README.md ("domain expired"). I found the content under http://usamadar.wordpress.com/2012/06/24/getting-around-browsers-same-origin-policy-sop-with-proxies-script-injection-jsonp-and-cors/ (although the nasty "domain expired" message is there, too).

Sorry for not making this a pull request.

**Comment by doedje** [comment]
I'll remove the link all together and try to encourage people to google their own answers... =] Thanx for letting me know!

**Comment by doedje** [comment]
finally updated the readme... ;)
