### ISSUE TITLE
the server doesn't work

### ISSUE THREAD

**Issue by yuanlin-work** [doedje/jquery.soap#96]
i had process the web service like this:
`import javax.jws.*;
import javax.xml.ws.Endpoint;

@WebService
public class WebServiceAjax{
	
	@WebMethod 
	@WebResult	
	public String say(@WebParam String name)
	{
		
		System.out.println(name);
		return "hello "+name;
		
	}
	
	public static void main(String[] args)
	{
		
		Endpoint.publish("http://localhost:9001/Service/WebServiceAjax", new WebServiceAjax());
		
		System.out.println("success");
	}
}`
and run the main method,and i can acccess the url 'http://localhost:9001/Service/WebServiceAjax?wsdl' who give me the right message,but when i use the query.soap.js to access the service,it give me some warns and make anything to happend,the warning message like this:
may 08, 2016 13:54:58  com.sun.xml.internal.ws.transport.http.server.WSHttpHandler handleExchange
warning: Cannot handle HTTP method: OPTIONS,and i don't know why

**Comment by yuanlin-work** [comment]
i had make it right by IE brower,but the chrome doesn't work anyway

**Comment by doedje** [comment]
Same origin policy, read the readme, it has some info on the matter. OPTIONS is part of CORS.
Two options:
1) make server CORS compatible
2) use a proxy on http://localhost
